gs_domain: https://docs.google.com/spreadsheets/d/
obs_base_dir: D:/boa_uniteam/OBSIDIAN/NECU/
tables:
    teams:
        name: Команда (Відповіді)
        gs_id: 1PW1F_xmz-qiHPRijApm_1q9R23ktLB5uf4KfK8m0A2k
        cols: [Акронім назви вашої команди, Повна назва вашої команди, 
        Представлення команди, Тип команди, Сфери діяльності команди, 
        Лідер команди, Помічник лідера команди, Склад команди, 
        Скорочена назва організації]
        title: Акронім назви вашої команди
        frontmatter: [Повна назва вашої команди, Тип команди, 
        Сфери діяльності команди, Лідер команди, Помічник лідера команди, 
        Скорочена назва організації]
        sections: [Представлення команди, Склад команди]
        not_required: []
        pers_name: [Лідер команди, Помічник лідера команди]
        linked: [Лідер команди, Помічник лідера команди, 
        Скорочена назва організації]
        subdir: TEAMS
    orgs:
        name: Організація (Відповіді)
        gs_id: 1-V2c3YU3aiCCfopX6GsFIzCK69pi8hfNtnC2pspAuqk
        cols: [Абревіатура або акронім вашої організації, Повна назва організації, 
        Тип організації, Реєстраційний індекс організації, 
        Дата заснування організації, Країна, Місто, Адреса організації, Телефон, 
        Е-пошта, Веб-сторінка]
        title: Абревіатура або акронім вашої організації
        frontmatter: [Повна назва організації, Тип організації, 
        Реєстраційний індекс організації, Дата заснування організації, Країна, 
        Місто, Адреса організації, Телефон, Е-пошта, Веб-сторінка]
        sections: [Представлення команди, Склад команди]
        not_required: []
        pers_name: []
        linked: []
        subdir: ORGS
    persons:
        name: Персона (Відповіді)
        gs_id: 1Htb_GxALIK8Jv3Sm3SIUI5yKYTC4aOZLcHAENY6p7LY
        cols: [ПІБ, День народження, Стать, Країна, Місто, Телефон, Е-пошта, 
        Персональний профіль, Скорочена назва організації, Посада]
        title: ПІБ
        frontmatter: [День народження, Стать, Країна, Місто, Телефон, Е-пошта, 
        Персональний профіль, Скорочена назва організації, Посада]
        sections: [Представлення команди, Склад команди]
        not_required: [День народження]
        pers_name: [ПІБ]
        linked: [ПІБ, Скорочена назва організації]
        subdir: PERSONS
    proj:
        name: Проєктна ідея (Відповіді)
        gs_id: 1MeTjAuEjHo56FsCepRZd9uan2Anz-jUQs0HKZziFLyg
        cols: [Код конкурсу Програми Горизонт Європа, Назва проекту, 
        Акронім вашої проєктної ідеї, Проблема, Рішення, Переваги вашого рішення, 
        Результати виконання, Очікуваний вплив, Етапи роботи, Потенційні партнери, 
        "Тривалість проєкту, міс", "Бюджет, тис. Євро", Команда проєкту, 
        ПІБ лідера проєкту, Організація]
        title: Акронім вашої проєктної ідеї
        frontmatter: [Код конкурсу Програми Горизонт Європа, Назва проекту, 
        "Тривалість проєкту, міс", "Бюджет, тис. Євро", Команда проєкту, 
        ПІБ лідера проєкту, Організація]
        sections: [Проблема, Рішення, Переваги вашого рішення, 
        Результати виконання, Очікуваний вплив, Етапи роботи, Потенційні партнери]
        not_required: []
        pers_name: [ПІБ лідера проєкту]
        linked: [Код конкурсу Програми Горизонт Європа, Команда проєкту, 
        ПІБ лідера проєкту, Організація]
        subdir: PROJ