# Опис конвертування вхідних таблиць Гугл Форми до нотаток Обсідіан. 
# Ключі (елементи) верхнього рівня означають тип вхідної таблиці і 
# відповідних нотаток Обсідіан.
teams:
    # Субфолдер Obsidian-сховища де зберігаються нотатки цього типу
    subdir: TEAMS
    # Ім'я файлу таблиці Google Sheets відповідей Google Forms
    name: Команда (Відповіді)
    # ВНазви всіх полів Google Forms (і стовпчиків таблиці Google 
    # Sheets)
    cols: [Акронім назви вашої команди, Повна назва вашої команди, 
    Представлення команди, Тип команди, Сфери діяльності команди, 
    Лідер команди, Помічник лідера команди, Склад команди, 
    Скорочена назва організації]
    # Назви полів Google Forms, що підуть як властивості до 
    # фронтматерії нотаток Obsidian
    frontmatter: [Повна назва вашої команди, Тип команди, 
    Сфери діяльності команди, Лідер команди, Помічник лідера команди, 
    Скорочена назва організації]
    # Назви полів Google Forms, що підуть як заголовки до нотаток 
    # Obsidian
    sections: [Представлення команди, Склад команди]
    # Список необов'язкових полів Google Forms
    not_required: []
    # Список полів Google Forms, що будуть перетворені перед 
    # розміщенням у нотатки
    pers_name: [Лідер команди, Помічник лідера команди]
    # Список полів Google Forms, що будуть перетворені як внутрішні 
    # посилання Obsidian перед розміщенням у нотатки
    linked: [Лідер команди, Помічник лідера команди, 
    Скорочена назва організації]
    # Зв'язування назви властивості нотатки Obsidian (ключ) з назвою 
    # поля Google Forms (значення). Відповідне значення поля Google 
    # Forms передається у значення властивості нотатки Obsidian
    label_refs:
        title: Акронім назви вашої команди
        acronym: Акронім назви вашої команди
        full_name: Повна назва вашої команди 
        team_type: Тип команди
        scope: Сфери діяльності команди
        leader: Лідер команди
        caddy: Помічник лідера команди
        org: Скорочена назва організації
    # У значення властивості нотатки Obsidian (ключ) передається 
    # значення ключа або це значення використовується для певного 
    # перетоврення
    label_vals:
        tags: [команда, доробити]
        link: 
        created: "%Y-%m-%d"
        updated: "%Y-%m-%d %H:%M"
orgs:
    subdir: ORGS
    name: Організація (Відповіді)
    cols: [Абревіатура або акронім вашої організації, Повна назва організації, 
    Тип організації, Реєстраційний індекс організації, 
    Дата заснування організації, Країна, Місто, Адреса організації, Телефон, 
    Е-пошта, Веб-сторінка]
    frontmatter: [Повна назва організації, Тип організації, 
    Реєстраційний індекс організації, Дата заснування організації, Країна, 
    Місто, Адреса організації, Телефон, Е-пошта, Веб-сторінка]
    sections: []
    not_required: []
    pers_name: []
    linked: []
    label_refs:
        title: Абревіатура або акронім вашої організації
        acronym: Абревіатура або акронім вашої організації
        full_name: Повна назва організації
        org_type: Тип організації
        vat_id: Реєстраційний індекс організації
        reg_date: Дата заснування організації
        country: Країна
        city: Місто
        addr: Адреса організації
        tel: Телефон
        email: Е-пошта
        web: Веб-сторінка
    label_vals:
        tags: [організація, доробити]
        created: "%Y-%m-%d"
        updated: "%Y-%m-%d %H:%M"
persons:
    subdir: PERSONS
    name: Персона (Відповіді)
    cols: [ПІБ, День народження, Стать, Країна, Місто, Телефон, Е-пошта, 
    Персональний профіль, Скорочена назва організації, Посада]
    frontmatter: [День народження, Стать, Країна, Місто, Телефон, Е-пошта, 
    Персональний профіль, Скорочена назва організації, Посада]
    sections: []
    not_required: [День народження]
    pers_name: [ПІБ]
    linked: [Скорочена назва організації]
    label_refs:
        title: ПІБ
        birthday: День народження
        sex: Стать
        country: Країна
        city: Місто
        tel: Телефон
        email: Е-пошта
        web: Персональний профіль
        org: Скорочена назва організації
        position: Посада
    label_vals:
        tags: [персона, доробити]
        created: "%Y-%m-%d"
        updated: "%Y-%m-%d %H:%M"
proj:
    subdir: PROJ
    name: Проєктна ідея (Відповіді)
    cols: [Акронім вашої проєктної ідеї, Код конкурсу Програми Горизонт Європа, Назва проекту, 
    Акронім вашої проєктної ідеї, Проблема, Рішення, Переваги вашого рішення, 
    Результати виконання, Очікуваний вплив, Етапи роботи, Потенційні партнери, 
    "Тривалість проєкту, міс", "Бюджет, тис. Євро", Команда проєкту, 
    ПІБ лідера проєкту, Організація]
    frontmatter: [Код конкурсу Програми Горизонт Європа, Назва проекту, 
    "Тривалість проєкту, міс", "Бюджет, тис. Євро", Команда проєкту, 
    ПІБ лідера проєкту, Організація]
    sections: [Проблема, Рішення, Переваги вашого рішення, 
    Результати виконання, Очікуваний вплив, Етапи роботи, Потенційні партнери]
    not_required: []
    pers_name: [ПІБ лідера проєкту]
    linked: [Код конкурсу Програми Горизонт Європа, Команда проєкту, 
    ПІБ лідера проєкту, Організація]
    label_refs:
        title: Акронім вашої проєктної ідеї
        call: Код конкурсу Програми Горизонт Європа
        name: Назва проекту
        proj: Акронім вашої проєктної ідеї
        duration: "Тривалість проєкту, міс"
        budget: "Бюджет, тис. Євро"
        team: Команда проєкту
    label_vals:
        tags: [проєкт/ідея, доробити]
        scope: 
        link: 
        created: "%Y-%m-%d"
        updated: "%Y-%m-%d %H:%M"
