teams:
    subdir: TEAMS
    name: Команда (Відповіді)
    cols: [Акронім назви вашої команди, Повна назва вашої команди, 
    Представлення команди, Тип команди, Сфери діяльності команди, 
    Лідер команди, Помічник лідера команди, Склад команди, 
    Скорочена назва організації]
    title: Акронім назви вашої команди
    frontmatter: [Повна назва вашої команди, Тип команди, 
    Сфери діяльності команди, Лідер команди, Помічник лідера команди, 
    Скорочена назва організації]
    sections: [Представлення команди, Склад команди]
    not_required: []
    pers_name: [Лідер команди, Помічник лідера команди]
    linked: [Лідер команди, Помічник лідера команди, 
    Скорочена назва організації]
    labels_ref:
        acronym: Акронім назви вашої команди
        full_name: Повна назва вашої команди 
        team_type: Тип команди
        scope: Сфери діяльності команди
        leader: Лідер команди
        caddy: Помічник лідера команди
        org: Скорочена назва організації
    labels_val:
        tags: [команда, доробити]
        link: 
        created: "%Y%m%d"
        updated: "%Y%m%d %H%M"
orgs:
    subdir: ORGS
    name: Організація (Відповіді)
    cols: [Абревіатура або акронім вашої організації, Повна назва організації, 
    Тип організації, Реєстраційний індекс організації, 
    Дата заснування організації, Країна, Місто, Адреса організації, Телефон, 
    Е-пошта, Веб-сторінка]
    title: Абревіатура або акронім вашої організації
    frontmatter: [Повна назва організації, Тип організації, 
    Реєстраційний індекс організації, Дата заснування організації, Країна, 
    Місто, Адреса організації, Телефон, Е-пошта, Веб-сторінка]
    sections: [Представлення команди, Склад команди]
    not_required: []
    pers_name: []
    linked: []
    labels_ref:
        acronym: Абревіатура або акронім вашої організації
        full_name: Повна назва організації
        org_type: Тип організації
        vat_id: Реєстраційний індекс організації, 
        reg_date: Дата заснування організації
        country: Країна
        city: Місто
        addr: Адреса організації
        tel: Телефон
        email: Е-пошта
        web: Веб-сторінка
    labels_val:
        tags: [організація, доробити]
        created: "%Y%m%d"
        updated: "%Y%m%d %H%M"
persons:
    subdir: PERSONS
    name: Персона (Відповіді)
    cols: [ПІБ, День народження, Стать, Країна, Місто, Телефон, Е-пошта, 
    Персональний профіль, Скорочена назва організації, Посада]
    title: ПІБ
    frontmatter: [День народження, Стать, Країна, Місто, Телефон, Е-пошта, 
    Персональний профіль, Скорочена назва організації, Посада]
    sections: [Представлення команди, Склад команди]
    not_required: [День народження]
    pers_name: [ПІБ]
    linked: [ПІБ, Скорочена назва організації]
    labels_ref:
        pib: ПІБ
        birthday: День народження
        sex: Стать
        country: Країна
        city: Місто
        tel: Телефон
        email: Е-пошта
        web: Персональний профіль
        org: Скорочена назва організації
        position: Посада
    labels_val:
        tags: [персона, доробити]
        created: "%Y%m%d"
        updated: "%Y%m%d %H%M"
proj:
    subdir: PROJ
    name: Проєктна ідея (Відповіді)
    cols: [Акронім вашої проєктної ідеї, Код конкурсу Програми Горизонт Європа, Назва проекту, 
    Акронім вашої проєктної ідеї, Проблема, Рішення, Переваги вашого рішення, 
    Результати виконання, Очікуваний вплив, Етапи роботи, Потенційні партнери, 
    "Тривалість проєкту, міс", "Бюджет, тис. Євро", Команда проєкту, 
    ПІБ лідера проєкту, Організація]
    title: Акронім вашої проєктної ідеї
    frontmatter: [Код конкурсу Програми Горизонт Європа, Назва проекту, 
    "Тривалість проєкту, міс", "Бюджет, тис. Євро", Команда проєкту, 
    ПІБ лідера проєкту, Організація]
    sections: [Проблема, Рішення, Переваги вашого рішення, 
    Результати виконання, Очікуваний вплив, Етапи роботи, Потенційні партнери]
    not_required: []
    pers_name: [ПІБ лідера проєкту]
    linked: [Код конкурсу Програми Горизонт Європа, Команда проєкту, 
    ПІБ лідера проєкту, Організація]
    labels_ref:
        call: Код конкурсу Програми Горизонт Європа
        name: Назва проекту
        proj: Акронім вашої проєктної ідеї
        duration: "Тривалість проєкту, міс"
        budget: "Бюджет, тис. Євро"
        team: Команда проєкту
    labels_val:
        tags: [проєкт/ідея, доробити]
        scope: 
        link: 
        created: "%Y%m%d"
        updated: "%Y%m%d %H%M"
