# -*- coding: utf-8 -*-
"""gs2note_run.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVn-DxLXuxSz92FBhsLonesv2elvMQqi

## Конвертування Google Sheets таблиці у Obsidian нотатки

GS2NOTE.PY -- Конвертор рядків таблиці Google Sheets (отриманої
з допомогою Google Form) у нотатки Obsidian. Налаштування і запуск ковертора
здійснюється двома мпособами:

1. з локального компа: $ python gs2note_run.py
2. у середовищі Google Colab: через запуск Jupyter Notebook `gs2note_run.ipynb`

Репозитарій: https://github.com/protw/obsidian_py<br>
Автор: https://protw.github.io/oleghbond<br>
Версія: 0.2 / Дата: 2025-03-29 / Ліцензія: GPL
"""

# @title Вхідні параметри

# @markdown Оберіть Обсідіан-сховище (**vault**):
vault = 'NECU' #@param ['NECU', 'NCP-NEB']

# @markdown Оберіть тип таблиці (**table**), що буде конвертований з Гугл форми
# @markdown до обраного сховища:
table = 'persons' #@param ['persons', 'teams', 'orgs', 'proj']

# ==== УВАГА! Цей розділ Colab комірки лише для адміна!! ====

# Якщо ви не знаєте призначення налаштувань нижче, або не впевнені в тому
# що знаєте, то нічого не чипайте
folders = {
    'base': '/content/drive',
    'vaults_base': '/MyDrive/OBSIDIAN/',
    'code_dir': 'obsidian-py/'
}

# В робочому положенні ВСІ елементи словника `cond` мають бут встановлені `True`
cond = {
    'is_dupl_in_vault': False, # Рекомендовано True, за замовчанням
    'is_dupl_in_table': True,  # Рекомендовано True, за замовчанням
    ## ---- СХОВАТИ ВІД КОРИСТУВАЧА ----
    'not_write_dupl':   False,  # Рекомендовано True, за замовчанням
    'is_clean_writing': False  # За замовчанням True
}

# @title Запуск конвертора
import os

!cd ~
if not os.path.isdir('obsidian_py'):
  !git clone --quiet https://github.com/protw/obsidian_py.git > /dev/null
os.chdir('obsidian_py')

import gs2note

conv = gs2note.run(vault=vault, table=table, folders=folders, cond=cond)