# -*- coding: utf-8 -*-
"""gs2note_main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVn-DxLXuxSz92FBhsLonesv2elvMQqi

## Конвертування Google Sheets таблиці у Obsidian нотатку
"""

# @title Вхідні параметри
folders = {
    'base': '/content/drive',
    'vaults_base': '/MyDrive/OBSIDIAN/',
    'code_dir': 'obsidian-py/',
    'vault_dir': 'NECU/'
}

cond = {
    'is_dupl_in_vault': False, # Рекомендовано True, за замовчанням
    'is_dupl_in_table': True,  # Рекомендовано True, за замовчанням
    ## ---- СХОВАТИ ВІД КОРИСТУВАЧА ----
    'not_write_dupl':   False,  # Рекомендовано True, за замовчанням
    'is_clean_writing': False  # За замовчанням True
}

table = 'persons' #@param ['persons', 'teams', 'orgs', 'proj']

# @title Запуск конвертора
import os
import gs2note_main

!cd ~
if not os.path.isdir('obsidian_py'):
  !git clone --quiet https://github.com/protw/obsidian_py.git > /dev/null
os.chdir('obsidian_py')

gs2note_main.run(table, folders=folders, cond=cond)