# -*- coding: utf-8 -*-
"""gs2note.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eVn-DxLXuxSz92FBhsLonesv2elvMQqi

## Конвертування Google Sheets таблиці у Obsidian нотатку

### Встановлення директорій
"""

import sys

folders = {
    'gdrive': 'D:/boa_uniteam',
    'shdrive': '/MyDrive/OBSIDIAN/',
    'code_dir': 'obsidian-py/',
    'data_dir': 'NECU/'
    }

from google.colab import drive
# Кореневі дректорії Гугл Диску
gdrive = '/content/drive'
# монтування Гугл Диску
drive.mount(gdrive)

# Конфігурація робочих директорій
code_dir = gdrive + folders['shdrive'] + folders['code_dir']
data_dir = gdrive + folders['shdrive'] + folders['data_dir']

# надання доступу до фолдера коду
sys.path.insert(0, code_dir)

"""### Зчитування Google Sheets таблиці"""

import obsidian_util as ou

# Константи алгоритму
config_file = code_dir + 'config.yml'
cred_file = code_dir + 'credentials.json'

# Яку таблицю зчитуємо
table = 'persons'
# Зчитування конфігураційного словника
conf = ou.read_yaml_config(config_file)
# Створення URL таблиці
table_url = ou.get_gs_table_url(conf, table)
# Зчитування таблиці Google Sheets за її URL
df = ou.read_gs_by_url(table_url, cred_file)

print(df)